image: python:3.7

stages:
- release

release:
  stage: release
  only:
    - tags
  tags:
   - linux
  before_script:
    - pip install git+https://github.com/Gustry/qgis-plugin-ci.git
  script:
    - qgis-plugin-ci package ${CI_COMMIT_TAG}
