variables:
  PLUGIN_NAME: "minimal"  # Must match plugin metadata.txt

stages:
- 🚀 Release

release:
  stage: 🚀 Release
  only:
    - tags
  tags:
   - factory
  before_script:
    - pip install git+https://github.com/Gustry/qgis-plugin-ci.git
  script:
    - qgis-plugin-ci package ${CI_COMMIT_TAG}
    - curl --header 'Content-Type:application/json' --header "PRIVATE-TOKEN:${USER_TOKEN}" --data '{"name":"'"${CI_COMMIT_TAG}"'","ref":"'"${CI_COMMIT_TAG}"'","tag_name":"'"${CI_COMMIT_TAG}"'","assets":{"links":[{ "name":"QGIS Package", "url":"'"${CI_JOB_URL}"'/artifacts/file/'"${PLUGIN_NAME}"'.'"${CI_COMMIT_TAG}"'.zip" }] } }' --request POST https://gitlab.com/api/v4/projects/328/releases
  artifacts:
    expose_as: 'package'
    # expire_in: 1 day
    paths:
      - ${PLUGIN_NAME}.${CI_COMMIT_TAG}.zip
