variables:
  PLUGIN_NAME: "minimal"  # Must match plugin metadata.txt

image: python:3.7

stages:
- 🚀 Release

release:
  stage: 🚀 Release
  only:
    - tags
  tags:
   - linux
  before_script:
    - pip install git+https://github.com/Gustry/qgis-plugin-ci.git
  script:
    - qgis-plugin-ci package ${CI_COMMIT_TAG}
    - curl --header 'Content-Type:application/json' --header "PRIVATE-TOKEN:${USER_TOKEN}" --data '{"name":"Release '"${CI_COMMIT_TAG}"'","ref":"master","tag_name":"'"${CI_COMMIT_TAG}"'","description":"Super nice release", "assets":{"links":[{ "name":"QGIS Package", "url":"https://google.com", "filepath":"/binaries/linux-amd64" }] } }' --request POST https://gitlab.com/api/v4/projects/18534198/releases
  artifacts:
    expose_as: 'package'
    expire_in: 1 day
    paths:
      - ${PLUGIN_NAME}.${CI_COMMIT_TAG}.zip
