variables:
  PLUGIN_NAME: "minimal"  # Must match plugin metadata.txt
  PROJECT_ID: "328"
  FACTORY_PRODUCT_NAME: "HELLO"

stages:
- 🚀 Release

tickets:
  stage: 🚀 Release
  image:
    name: $REGISTRY_URI/infra/ci-tools
  variables:
    DEBUG: "True"
  script:
    - pwd
    - ls -al
    # - create_ticket.py product_name version_number ${GITLAB_SLUG} ${CI_PIPELINE_ID} ${USER_TOKEN}
  tags:
    - factory-plain

lizmap_box:
  stage: 🚀 Release
  allow_failure: true
  only:
    - tags
  script:
    - >
      curl
      --header 'Content-Type:application/json'
      --header "PRIVATE-TOKEN:${USER_TOKEN}"
      --data '{
      "id":330,
      "title":"Nouvelle version '"${FACTORY_PRODUCT_NAME}"' : '"${CI_COMMIT_REF_NAME}"'",
      "description":"FYI : nouvelle version '"${FACTORY_PRODUCT_NAME}"' '"${CI_COMMIT_REF_NAME}"' 👍"}'
      --request POST https://projects.3liz.org/api/v4/projects/330/issues
  tags:
    - factory

release:
  stage: 🚀 Release
  only:
    - tags
  tags:
   - factory
  before_script:
    - git config --global user.email "notused@but.useful"
    - git config --global user.name "Wonder why you need that"
    - PATH=$PATH:/home/factory-runner/.local/bin
    - pip install --upgrade --force-reinstall git+https://github.com/Gustry/qgis-plugin-ci.git
  script:
    - qgis-plugin-ci package ${CI_COMMIT_TAG}
    - curl --header 'Content-Type:application/json' --header "PRIVATE-TOKEN:${USER_TOKEN}" --data '{"name":"'"${CI_COMMIT_TAG}"'","ref":"'"${CI_COMMIT_TAG}"'","tag_name":"'"${CI_COMMIT_TAG}"'","assets":{"links":[{ "name":"QGIS Package", "url":"'"${CI_JOB_URL}"'/artifacts/file/'"${PLUGIN_NAME}"'.'"${CI_COMMIT_TAG}"'.zip" }] } }' --request POST https://projects.3liz.org/api/v4/projects/${PROJECT_ID}/releases
  artifacts:
    expose_as: 'package'
    expire_in: 1 hour
    paths:
      - ${PLUGIN_NAME}.${CI_COMMIT_TAG}.zip
