variables:
  PLUGIN_NAME: "minimal"  # Must match plugin metadata.txt
  PROJECT_ID: "328"

stages:
- 🚀 Release

release:
  stage: 🚀 Release
  only:
    - tags
  tags:
   - factory
  before_script:
    - ls -l src/metadata.txt
    - PATH=$PATH:/home/factory-runner/.local/bin
    - pip install git+https://github.com/Gustry/qgis-plugin-ci.git
  script:
    - cat src/metadata.txt
    - qgis-plugin-ci package ${CI_COMMIT_TAG}
    - cat src/metadata.txt
    - curl --header 'Content-Type:application/json' --header "PRIVATE-TOKEN:${USER_TOKEN}" --data '{"name":"'"${CI_COMMIT_TAG}"'","ref":"'"${CI_COMMIT_TAG}"'","tag_name":"'"${CI_COMMIT_TAG}"'","assets":{"links":[{ "name":"QGIS Package", "url":"'"${CI_JOB_URL}"'/artifacts/file/'"${PLUGIN_NAME}"'.'"${CI_COMMIT_TAG}"'.zip" }] } }' --request POST https://projects.3liz.org/api/v4/projects/${PROJECT_ID}/releases
  artifacts:
    expose_as: 'package'
    expire_in: 1 hour
    paths:
      - ${PLUGIN_NAME}.${CI_COMMIT_TAG}.zip
