language: python

dist: bionic

python:
  - 3.7

jobs:
  include:
  - name: Job 1
    install:
      - pip3 install -r requirements.txt
    script: qgis-plugin-ci --version
  - name: Job 2
    script: echo "Running job 2"

deploy:
  provider: script
  script: ./deploy.sh ${TRAVIS_TAG} ${GH_TOKEN}
  on:
    tags: true