language: python

dist: bionic

python:
  - 3.7

jobs:
  include:
  - name: Job 1
    script: echo "Running job 1"
  - name: Job 2
    script: echo "Running job 2"

install:
  - pip3 install -r requirements.txt

script: qgis-plugin-ci --version

deploy:
  provider: script
  script: ./deploy.sh ${TRAVIS_TAG} ${GH_TOKEN}
  on:
    tags: true