language: python

dist: bionic

python: 3.7

env:
  - FOO=QGIS_3.4
#   - FOO=QGIS_latest
install:
  - pip3 install qgis-plugin-ci
script: echo $FOO

jobs:
  include:
    - stage: Run tests QGIS Server
      name: Job 2
      install:
        - pip3 install qgis-plugin-ci
      script:
        - echo "Running job 2"
        - qgis-plugin-ci -v
#    - stage: Deploy
#      name: Job 3
#      install:
#        - pip3 install -r requirements.txt
#      script: qgis-plugin-ci --version
    - stage: Final deploy
      name: Yahoo

      before_deploy:
        - export RELEASE_TITLE="Release of $TRAVIS_TAG"
        - export RELEASE_DESC=BLABLA

      deploy:

        - provider: releases
          edge: true
          file: .
          name: ${RELEASE_TITLE}
          release_notes: ${RELEASE_DESC}
          api_key: ${GH_TOKEN}
          skip_cleanup: true
          on:
            tags: true

        - provider: script
          script: ./deploy.sh ${TRAVIS_TAG} ${GH_TOKEN}
          on:
            tags: true
