dist: bionic

language: python

python: 3.7

services:
  - docker

branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/

env:
  - FOO=QGIS_3.4
#   - FOO=QGIS_latest
install:
  - pip3 install git+https://github.com/Gustry/qgis-plugin-ci.git
script: echo $FOO

jobs:
  include:
#    - stage: Run tests QGIS Server
#      name: Job 2
#      install:
#        - pip3 install git+https://github.com/Gustry/qgis-plugin-ci.git
#      script:
#        - echo "Running job 2"
#        - qgis-plugin-ci -v
#    - stage: Deploy
#      name: Job 3
#      install:
#        - pip3 install -r requirements.txt
#      script: qgis-plugin-ci --version

    - stage: Deploy
      if: tag IS present
      name: Create release, plugins.qgis.org
      install:
        - pip3 install git+https://github.com/Gustry/qgis-plugin-ci.git
      before_deploy:
        - export RELEASE_TITLE="$TRAVIS_TAG"
        - BODY=eval qgis-plugin-ci changelog ${TRAVIS_TAG}
        - export ${BODY}
        # - export BODY=eval ${BODY_COMMAND}
      script:
        - qgis-plugin-ci -v
      deploy:
        - provider: releases
          edge: true
          file: .
          name: ${RELEASE_TITLE}
          release_notes: ${BODY}
          api_key: ${GH_TOKEN}
          on:
            tags: true

        - provider: script
          script: qgis-plugin-ci release ${TRAVIS_TAG} --github-token ${GH_TOKEN} --transifex-token ${TX_TOKEN} --create-plugin-repo --allow-uncommitted-changes
          on:
            tags: true

        - provider: script
          skip_cleanup: true
          script: ./push.sh
          on:
            tags: true
