language: python

dist: bionic

python:
  - 3.7

jobs:
  include:
    - stage: Run tests QGIS Desktop
      env:
        - FOO=QGIS_3.4
        - FOO=QGIS_latest
      name: Job 1
      install:
        - pip3 install -r requirements.txt
      script: echo $FOO
    - name: QGIS Server
      install:
        - pip3 install mock
      script: echo "Running job 2"
    - stage: Deploy
      name: Job 3
      install:
        - pip3 install -r requirements.txt
      script: qgis-plugin-ci --version

deploy:
  provider: script
  script: ./deploy.sh ${TRAVIS_TAG} ${GH_TOKEN}
  on:
    tags: true