language: python

dist: bionic

python:
  - 3.7

env:
  - FOO=QGIS_3.4
  - FOO=QGIS_latest
install:
  - pip3 install -r requirements.txt
script: echo $FOO

jobs:
  include:
    - stage: Run tests QGIS Server
      name: Job 2
      install:
        - pip3 install mock
      script: echo "Running job 2"
    - stage: Deploy
      name: Job 3
      install:
        - pip3 install -r requirements.txt
      script: qgis-plugin-ci --version
    - stage: Final deploy
      name: Yahoo
      deploy:

        - provider: releases
          api_key: ${GH_TOKEN}
          skip_cleanup: true
          on:
            tags: true

        - provider: script
          script: ./deploy.sh ${TRAVIS_TAG} ${GH_TOKEN}
          on:
            tags: true