name: "Push Notification"

on:
  fork:
  watch:
    types: [started]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: irc push
        uses: rectalogic/notify-irc@v1
        with:
          channel: "#mychannel"
          nickname: 3liz-bot
          message: |
            ${{ github.actor }} pushed ${{ github.event.ref }} ${{ github.event.compare }}
            ${{ join(github.event.commits.*.message) }}
