name: 🚀 Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:

      - name: Get source code
        uses: actions/checkout@v3

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Debug
        run: echo ${{ env.RELEASE_VERSION }}

      - name: Changelog
        id: changelog
        uses: Gustry/changelog-release@0.1.0
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          changelog_file: 'CHANGELOG.md'
          add_emojis: True

      - name: Create release on GitHub
        uses: ncipollo/release-action@v1.10.0
        with:
          body: ${{ steps.changelog.outputs.markdown }}
          allowUpdates: true
